version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    allow:
      - dependency-type: "all"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "django"
          - "django-crispy-forms"
          - "django-registration"
          - "django-ses"
          - "djangorestframework"
          - "schedule"
          - "stripe"
          - "tw-complex"
          - "uwsgi"
      main-dependencies:
        patterns:
          - "django"
          - "django-crispy-forms"
          - "django-registration"
          - "django-ses"
          - "djangorestframework"
          - "schedule"
          - "stripe"
          - "tw-complex"
          - "uwsgi"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
