repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/myint/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake
        args:
          [
            "--recursive",
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args:
          [
            "--py3-plus",
            "--py36-plus",
            "--py37-plus",
            "--py38-plus",
            "--py39-plus",
            "--py310-plus",
          ]
        files: ".*"

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8

  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.0b1"
    hooks:
      - id: poetry-export
        args: ["--without-hashes"]
