repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/myint/autoflake
    rev: "v1.7.7"
    hooks:
      - id: autoflake
        args:
          [
            "--recursive",
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args:
          [
            "--py3-plus",
            "--py36-plus",
            "--py37-plus",
            "--py38-plus",
            "--py39-plus",
            "--py310-plus",
            "--py311-plus",
          ]
        files: ".*"

  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8

  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.2"
    hooks:
      - id: poetry-export
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
            "--without-hashes",
          ]

  - repo: https://github.com/rafsaf/pyproject-tag-check
    rev: "0.2.0"
    hooks:
      - id: pyproject-tag-check
        args:
          - https://github.com/rafsaf/Tribal-Wars-Planer
