repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: "23.11.0"
    hooks:
      - id: black

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.1.6
  #   hooks:
  #     - id: ruff
  #       args: [--fix]

  - repo: https://github.com/rafsaf/pyproject-tag-check
    rev: "1.0.0"
    hooks:
      - id: pyproject-tag-check
        always_run: true
        args:
          - https://github.com/rafsaf/Tribal-Wars-Planer
