version: "3.3"

services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
  web:
    depends_on:
      - postgres
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - .env
