version: "3.3"

services:
  postgres:
    restart: always
    image: postgres
    volumes:
      - ./data_postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  web:
    depends_on:
      - postgres
    restart: always
    image: rafsaf/twp-server:latest
    ports:
      - 7999:80
    healthcheck:
      test: curl --fail http://localhost/en/api/healthcheck/ || exit 1
      interval: 25s
      retries: 2
      start_period: 30s
      timeout: 10
    environment:
      - SECRET_KEY=zaq12wsx3edc
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com

  cronjobs:
    depends_on:
      - postgres
    restart: always
    image: rafsaf/twp-cronjobs:latest
    command: python -m base.run_cronjobs