version: "3.9"

services:
  web:
    depends_on:
      - postgres
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - .env
