version: "3.4"

services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=25
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    restart: always
    image: postgres
    volumes:
      - twp_stg_postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

  web:
    depends_on:
      - postgres
    restart: always
    image: rafsaf/twp-server:latest
    labels:
      - "traefik.enable=true"
      # static
      - "traefik.http.routers.web-static.rule=Host(`${MAIN_DOMAIN}`) && PathPrefix(`/static/`)"
      - "traefik.http.routers.web-static.entrypoints=websecure"
      - "traefik.http.routers.web-static.tls.certresolver=myresolver"
      - "traefik.http.middlewares.cache-headers.headers.customresponseheaders.Cache-Control=public,max-age=2592000"
      - "traefik.http.routers.web-static.middlewares=cache-headers"
      # default
      - "traefik.http.routers.web.rule=Host(`${MAIN_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost/en/api/healthcheck/ || exit 1
      interval: 60s
      retries: 2
      start_period: 30s
      timeout: "10"
    volumes:
      - "twp_stg_logs:/var/log"
      - "twp_stg_logs:/build/logs"

  traefik:
    image: "traefik:v2.4"
    restart: always
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # test certificates
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${DEFAULT_FROM_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "twp_stg_letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  cronjobs:
    restart: always
    image: rafsaf/twp-cronjobs:latest
    command: python -m base.run_cronjobs
    env_file:
      - .env
    volumes:
      - "twp_stg_logs:/app/logs"

volumes:
  twp_stg_postgresql:
  twp_stg_logs:
  twp_stg_letsencrypt: