version: "3.3"

services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  webhook:
    image: thecatlady/webhook
    container_name: webhook
    command: -verbose -hooks=hooks.json -hotreload
    volumes:
      - ./webhook/:/config:ro
    ports:
      - 9000:9000
