version: "3.4"

services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=20
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  web:
    restart: always
    image: rafsaf/twp-server:latest
    labels:
      - "traefik.enable=true"
      # default
      - "traefik.http.routers.web.rule=Host(`${MAIN_DOMAIN}`, `${SUB_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      # redirect domain to other
      - "traefik.http.middlewares.redirect-web.redirectregex.regex=^(https?://)${SUB_DOMAIN}/(.*)"
      - "traefik.http.middlewares.redirect-web.redirectregex.replacement=$${1}${MAIN_DOMAIN}/$${2}"
      - "traefik.http.middlewares.redirect-web.redirectregex.permanent=true"
      - "traefik.http.routers.web.middlewares=redirect-web"
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost/api/healthcheck/ || exit 1
      interval: 15s
      retries: 2
      start_period: 30s
      timeout: "10"
    volumes:
      - "twp_prd_logs:/build/logs"
      - "twp_prd_media:/build/media"

  web2:
    restart: always
    image: rafsaf/twp-server:latest
    labels:
      - "traefik.enable=true"
      # default
      - "traefik.http.routers.web.rule=Host(`${MAIN_DOMAIN}`, `${SUB_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      # redirect domain to other
      - "traefik.http.middlewares.redirect-web.redirectregex.regex=^(https?://)${SUB_DOMAIN}/(.*)"
      - "traefik.http.middlewares.redirect-web.redirectregex.replacement=$${1}${MAIN_DOMAIN}/$${2}"
      - "traefik.http.middlewares.redirect-web.redirectregex.permanent=true"
      - "traefik.http.routers.web.middlewares=redirect-web"
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost/api/healthcheck/ || exit 1
      interval: 15s
      retries: 2
      start_period: 30s
      timeout: "10"
    volumes:
      - "twp_prd_logs:/build/logs"
      - "twp_prd_media:/build/media"

  traefik:
    image: "traefik:v2.6"
    restart: always
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # test certificates
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${DEFAULT_FROM_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "twp_prd_letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  cronjobs:
    restart: always
    image: rafsaf/twp-server:latest
    command: python manage.py runcronjobs
    env_file:
      - .env
    volumes:
      - "twp_stg_logs:/build/logs"

volumes:
  twp_prd_logs:
  twp_prd_letsencrypt:
  twp_prd_media: