version: "3.4"

services:
  postgres_dev:
    image: postgres
    restart: "unless-stopped"
    volumes:
      - twp_dev_postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  cronjobs_dev:
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile.cronjobs
    command: python -m base.run_cronjobs
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - .env
    volumes:
      - "./logs:/app/logs"

volumes:
  twp_dev_postgresql: