version: "3.3"

services:
  postgres_dev:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cronjobs_dev:
    build:
      context: ./
      dockerfile: Dockerfile.cronjobs
    command: python -m base.run_cronjobs
    env_file:
      - .env
    environment: 
      - POSTGRES_HOST=postgres_dev
      - DJANGO_SETTINGS_MODULE=tribal_wars_planer.settings