version: "3.7"

services:
  postgres_dev:
    image: postgres:14
    restart: "unless-stopped"
    volumes:
      - twp_dev_postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  cronjobs_dev:
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: bash /build/scripts/init_cronjobs.sh
    environment:
      - POSTGRES_HOST=postgres_dev
    env_file:
      - .env
    volumes:
      - "./logs:/build/logs"

  stripe_cli:
    image: stripe/stripe-cli:latest
    restart: "unless-stopped"
    command: listen --forward-to http://localhost:8000/api/stripe-webhook/
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    network_mode: "host"

volumes:
  twp_dev_postgresql: