services:
  postgres:
    restart: always
    image: postgres:15
    volumes:
      - twp_local_postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  web:
    depends_on:
      - postgres
    restart: always
    image: rafsaf/twp-server:latest
    ports:
      - 7999:80
    environment:
      - SECRET_KEY=zaq12wsx3edc
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com

  cronjobs:
    depends_on:
      - postgres
    restart: always
    image: rafsaf/twp-server:latest
    command: bash /build/scripts/init_cronjobs.sh

volumes:
  twp_local_postgresql:
