version: "3.3"

services:
  postgres:
    restart: "unless-stopped"
    image: postgres
    volumes:
      - ./data_richdev_postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./metrics:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus-dev.yml

  web:
    depends_on:
      - postgres
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 7998:80
    environment:
      - SECRET_KEY=askldjasd0987123987
      - SUB_DOMAIN=web

  cronjobs:
    depends_on:
      - postgres
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile.cronjobs
    command: python -m base.run_cronjobs
    volumes:
      - "./logs:/app/logs"

  master_locust:
    restart: "unless-stopped"
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./perf:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://web:80
  
  worker_locust:
    restart: "unless-stopped"
    image: locustio/locust
    volumes:
      - ./perf:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master_locust

volumes:
  prometheus-data: