[tool.poetry]
name = "tribal_wars_planer"
version = "2.0.0"
description = ""
authors = ["rafsaf <rafal.safin12@gmail.com>"]

[tool.poetry.dependencies]
python = ">3.10,<3.11"

Django = "4.0.2"
django-crispy-forms = "1.14.0"
django-registration = "3.2"
djangorestframework = "3.13.1"
django-ses = "2.4.0"

python-dateutil = "2.8.2"
python-dotenv = "0.19.2"
psycopg2 = "2.9.3"
stripe = "2.65.0"
tw-complex = "1.0.3"
Js2Py = "0.71"
fpdf = "1.7.2"
prometheus-client = "0.13.1"


[tool.poetry.dev-dependencies]
black = {version = "^21.5b1", allow-prereleases = true}
coverage = {extras = ["toml"], version = "^5.5"}
isort = "^5.9.3"
flake8 = "^3.9.2"
autoflake = "^1.4"
pytest-django = "^4.4.0"
requests-mock = "^1.9.3"
locust = "^2.5.1"
schedule = "^1.1.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tribal_wars_planer.settings"
minversion = "6.0"
addopts = "-v"
testpaths = [
    "base",
    "rest_api",
    "tribal_wars_planer",
    "utils",
]

[tool.coverage.run]
source = [   
    "base",
    "rest_api",
    "tribal_wars_planer",
    "utils",
]
omit = [
    "*__init__.py*",
    "*/migrations/*",
    "*/tests/*",
    "tribal_wars_planer/wsgi.py",
    "tribal_wars_planer/asgi.py",
]

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
