[tool.poetry]
authors = ["rafsaf <rafal.safin@rafsaf.pl>"]
description = "Tribal Wars Planer django app, professional tool for creating outlines for off-game coordinators."
name = "tribal_wars_planer"
version = "4.31.0"

[tool.poetry.dependencies]
python = ">3.10,<3.12"

crispy-bootstrap4 = "^2022.1"
django = "^4.2.5"
django-crispy-forms = "^2.0"
django-registration = "^3.3"
django-ses = "^3.3.0"
djangorestframework = "^3.14.0"

botocore = "^1.31.45"
diskcache = "^5.6.3"
fpdf = "^1.7.2"
prometheus-client = "^0.17.1"
psutil = "^5.9.4"
psycopg = { extras = ["c"], version = "^3.1.9" }
python-dateutil = "^2.8.2"
python-dotenv = "^1.0.0"
schedule = "^1.1.0"
stripe = "^6.2.0"
tw-complex = "^1.1.0"
uwsgi = "^2.0.21"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.2.1"
black = "^23.9.1"
coverage = "^7.3.1"
django-types = "^0.17.0"
flake8 = "^6.0.0"
freezegun = "^1.2.2"
isort = "^5.12.0"
locust = "^2.13.2"
pre-commit = "^3.4.0"
pytest-django = "^4.5.2"
pytest-xdist = "^3.1.0"
pyupgrade = "^3.3.1"
requests-mock = "^1.10.0"
pytest-cov = "^4.1.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tribal_wars_planer.settings"
addopts = "-v --cov --cov-report xml --cov-report term-missing -n auto"
minversion = "6.0"
testpaths = ["base", "rest_api", "tribal_wars_planer", "utils"]

[tool.coverage.run]
omit = [
  "*__init__.py*",
  "*/migrations/*",
  "*/tests/*",
  "tribal_wars_planer/wsgi.py",
  "tribal_wars_planer/asgi.py",
]
source = ["base", "rest_api", "tribal_wars_planer", "utils"]

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
