[tool.poetry]
name = "tribal_wars_planer"
version = "2.0.0"
description = ""
authors = ["rafsaf <rafal.safin12@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"

Django = "3.2.11"
django-crispy-forms = "1.13.0"
django-recaptcha = "2.0.6"
django-registration = "3.2"
djangorestframework = "3.13.1"
django-ses = "2.3.1"

Pillow = "^9.0.0"
python-dateutil = "2.8.2"
python-dotenv = "0.19.2"
psycopg2 = "2.9.3"
requests = "2.27.1"
stripe = "2.64.0"
tw-complex = "0.3.0"
Js2Py = "0.71"
schedule = "1.1.0"
fpdf = "1.7.2"
prometheus-client = "0.12.0"


[tool.poetry.dev-dependencies]
black = {version = "^21.5b1", allow-prereleases = true}
coverage = {extras = ["toml"], version = "^5.5"}
isort = "^5.9.3"
flake8 = "^3.9.2"
autoflake = "^1.4"
pytest-django = "^4.4.0"
requests-mock = "^1.9.3"
locust = "^2.5.1"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tribal_wars_planer.settings"
minversion = "6.0"
addopts = ""
testpaths = [
    "base",
    "rest_api",
    "tribal_wars_planer",
    "utils",
]

[tool.coverage.run]
source = [   
    "base",
    "rest_api",
    "tribal_wars_planer",
    "utils",
]
omit = [
    "*__init__.py*",
    "*/migrations/*",
    "*/tests/*",
    "tribal_wars_planer/wsgi.py",
    "tribal_wars_planer/asgi.py",
]

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
