[tool.poetry]
authors = ["rafsaf <rafal.safin12@gmail.com>"]
description = "Tribal Wars Planer django app, professional tool for creating outlines for off-game coordinators."
name = "tribal_wars_planer"
version = "2"

[tool.poetry.dependencies]
python = ">3.10,<3.11"

Django = "^4.0.6"
django-crispy-forms = "1.14.0"
django-registration = "3.3"
django-ses = "3.1.0"
djangorestframework = "3.13.1"

Js2Py = "0.71"
diskcache = "^5.4.0"
fpdf = "1.7.2"
prometheus-client = "0.14.1"
psutil = "^5.9.0"
psycopg2 = "2.9.3"
python-dateutil = "2.8.2"
python-dotenv = "0.20.0"
schedule = "^1.1.0"
stripe = "3.5.0"
tw-complex = "1.0.3"
uWSGI = "^2.0.20"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^22.3.0"
coverage = {extras = ["toml"], version = "^6.4"}
flake8 = "^4.0.1"
freezegun = "^1.2.1"
isort = "^5.10.1"
pytest-django = "^4.5.2"
requests-mock = "^1.9.3"
schedule = "^1.1.0"
pre-commit = "^2.19.0"
pyupgrade = "^2.34.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tribal_wars_planer.settings"
addopts = "-v"
minversion = "6.0"
testpaths = [
  "base",
  "rest_api",
  "tribal_wars_planer",
  "utils",
]

[tool.coverage.run]
omit = [
  "*__init__.py*",
  "*/migrations/*",
  "*/tests/*",
  "tribal_wars_planer/wsgi.py",
  "tribal_wars_planer/asgi.py",
]
source = [
  "base",
  "rest_api",
  "tribal_wars_planer",
  "utils",
]

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
