[tool.poetry]
name = "tribal_wars_planer"
version = "2.0.0"
description = ""
authors = ["rafsaf <rafal.safin12@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"

Django = "3.2.7"
django-crispy-forms = "1.12.0"
django-crontab = "0.7.1"
django-markdownx = "3.0.1"
django-recaptcha = "2.0.6"
django-registration = "3.2"
djangorestframework = "3.12.4"
django-ses = "2.2.1"

Pillow = "8.3.2"
python-dateutil = "2.8.2"
python-dotenv = "0.19.0"
psycopg2 = "2.9.1"
requests = "2.26.0"
stripe = "2.60.0"
tw-complex = "0.3.0"
Js2Py = "0.71"


[tool.poetry.dev-dependencies]
black = {version = "^21.5b1", allow-prereleases = true}
coverage = {extras = ["toml"], version = "^5.5"}
isort = "^5.9.3"
flake8 = "^3.9.2"
autoflake = "^1.4"
pytest-django = "^4.4.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tribal_wars_planer.settings"
minversion = "6.0"
addopts = ""
testpaths = [
    "base",
    "rest_api",
    "tribal_wars_planer",
    "utils",
]

[tool.coverage.run]
source = [   
    "base",
    "rest_api",
    "tribal_wars_planer",
    "utils",
]
omit = [
    "*__init__.py*",
    "*/migrations/*",
    "*/tests/*",
]

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
