[tool.poetry]
authors = ["rafsaf <rafal.safin@rafsaf.pl>"]
description = "Tribal Wars Planer django app, professional tool for creating outlines for off-game coordinators."
name = "tribal_wars_planer"
version = "4.40.0"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"

crispy-bootstrap4 = "^2023.1"
django = "^5.0"
django-crispy-forms = "^2.0"
django-registration = "^3.3"
django-ses = "^3.3.0"
djangorestframework = "^3.14.0"

botocore = "^1.31.74"
diskcache = "^5.6.3"
fpdf = "^1.7.2"
prometheus-client = "^0.19.0"
psutil = "^5.9.6"
psycopg = { extras = ["c"], version = "^3.1.12" }
python-dateutil = "^2.8.2"
python-dotenv = "^1.0.0"
schedule = "^1.2.1"
stripe = "^7.12.0"
uwsgi = "^2.0.23"
numpy = "^1.26.1"
scipy = "^1.11.3"
beautifulsoup4 = "^4.12.2"

[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
coverage = "^7.3.2"
freezegun = "^1.2.2"
pre-commit = "^3.5.0"
pytest-django = "^4.6.0"
pytest-xdist = "^3.1.0"
requests-mock = "^1.10.0"
pytest-cov = "^4.1.0"
mypy = "^1.7.1"
ruff = "^0.1.7"
types-requests = "^2.31.0.10"
types-python-dateutil = "^2.8.19.14"
types-pytz = "^2023.3.1.1"
django-stubs = "^4.2.7"
django-stubs-ext = "^4.2.7"
djangorestframework-stubs = "^3.14.5"
types-markdown = "^3.5.0.3"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tribal_wars_planer.settings"
addopts = "-v --cov --no-migrations --cov-report xml --cov-report term-missing -n auto"
minversion = "6.0"
testpaths = ["base", "rest_api", "tribal_wars_planer", "utils"]

[tool.coverage.run]
omit = [
  "*__init__.py*",
  "*/migrations/*",
  "*/tests/*",
  "tribal_wars_planer/wsgi.py",
  "tribal_wars_planer/asgi.py",
]
source = ["base", "rest_api", "tribal_wars_planer", "utils"]

[tool.ruff]
# pycodestyle, pyflakes, isort, pylint, pyupgrade
select = ["E", "W", "F", "I", "PL", "UP"]
ignore = ["E501", "PLR2004", "PLR0915"]
target-version = "py312"

[tool.ruff.pylint]
max-args = 12
max-branches = 20

[tool.mypy]
python_version = "3.12"
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true
# strict = true
check_untyped_defs = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "tribal_wars_planer.settings"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
