[tool.poetry]
authors = ["rafsaf <rafal.safin@rafsaf.pl>"]
description = "Tribal Wars Planer django app, professional tool for creating outlines for off-game coordinators."
name = "tribal_wars_planer"
version = "4.16.0"

[tool.poetry.dependencies]
python = ">3.10,<3.12"

django = "^4.1.6"
django-crispy-forms = "^1.14.0"
django-registration = "^3.3"
django-ses = "^3.3.0"
djangorestframework = "^3.14.0"

diskcache = "^5.4.0"
fpdf = "^1.7.2"
prometheus-client = "^0.16.0"
psutil = "^5.9.4"
psycopg2 = "^2.9.5"
python-dateutil = "^2.8.2"
python-dotenv = "^0.21.0"
schedule = "^1.1.0"
stripe = "^5.1.1"
tw-complex = "^1.1.0"
uwsgi = "^2.0.21"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.0.0"
black = "^22.12.0"
coverage = { extras = ["toml"], version = "^6.5.0" }
django-types = "^0.16.0"
flake8 = "^6.0.0"
freezegun = "^1.2.2"
isort = "^5.12.0"
locust = "^2.13.2"
pre-commit = "^2.20.0"
pytest-django = "^4.5.2"
pytest-xdist = "^3.1.0"
pyupgrade = "^3.3.1"
requests-mock = "^1.10.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tribal_wars_planer.settings"
addopts = "-v"
minversion = "6.0"
testpaths = ["base", "rest_api", "tribal_wars_planer", "utils"]

[tool.coverage.run]
omit = [
  "*__init__.py*",
  "*/migrations/*",
  "*/tests/*",
  "tribal_wars_planer/wsgi.py",
  "tribal_wars_planer/asgi.py",
]
source = ["base", "rest_api", "tribal_wars_planer", "utils"]

[tool.isort]
profile = "black"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
