site_name: "Tribal Wars Planer"
site_url: "https://plemiona-planer.pl/en/documentation/"
docs_dir: "../../docs/en"
site_dir: "../../../generated_docs/en/documentation"
repo_url: https://github.com/rafsaf/Tribal-Wars-Planer
edit_uri: "edit/main/docs/docs/en"

theme:
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - navigation.footer
  name: material
  custom_dir: "../../overrides/"
  logo: assets/images/favicon.jpg
  favicon: assets/images/favicon.jpg
  language: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rafsaf/Tribal-Wars-Planer
    - icon: fontawesome/brands/discord
      link: https://discord.gg/g5pcsCteCT
  alternate:
    - name: Polski
      link: /pl/documentation/
      lang: pl
    - name: English
      link: /en/documentation/
      lang: en

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path:
        - ./docs/overrides/data/
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: en
  - glightbox
  - social

nav:
  - Back to site: "https://plemiona-planer.pl"
  - 1. Test world:
      - first_steps/index.md
      - first_steps/step_1_create_outline.md
      - first_steps/step_2_choose_tribes.md
      - first_steps/step_3_fill_data.md
      - first_steps/step_4_save_targets_and_settings.md
      - first_steps/step_5_add_weights_to_target.md
      - first_steps/step_6_set_time_finish.md
      - first_steps/step_7_results_tab.md
  - 2. Installing the necessary scripts: scripts/index.md
  - 3. Basic: primary/index.md
  - 4. Advanced: advanced/index.md
