name: Push latest images to dockerhub and redeploy prod

on:
  release:
    types:
      - created

jobs:
  push_latest_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push latest twp-server image
        uses: docker/build-push-action@v4
        with:
          target: build
          context: .
          push: true
          tags: rafsaf/twp-server:latest
          platforms: linux/amd64,linux/arm64

  redeploy_prod:
    runs-on: ubuntu-latest
    needs: push_latest_image_to_dockerhub
    steps:
      - uses: actions/checkout@v3
      - name: Redeploy prod server
        run: |
          curl -k -X POST https://${{ secrets.PROD_HOOK_IP }}:9000/hooks/redeploy -H "Content-Type: application/json" -d '{"secret": "${{ secrets.PROD_HOOK_SECRET }}"}'
