name: Push latest images to dockerhub and redeploy prod

on:
  release:
    types:
      - created

jobs:
  push_latest_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push latest twp-server image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.prod
          context: .
          push: true
          tags: rafsaf/twp-server:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push latest twp-cronjobs image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.cronjobs
          context: .
          push: true
          tags: rafsaf/twp-cronjobs:latest
          platforms: linux/amd64,linux/arm64

      - name: Redeploy prod server
        run: |
          bash scripts/redeploy_env_webhook.sh ${{ secrets.PROD_HOOK_IP }} ${{ secrets.PROD_HOOK_SECRET }}
