name: Manual push latest images to dockerhub and redeploy prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "latest"

jobs:
  push_latest_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push latest twp-server image
        uses: docker/build-push-action@v6
        with:
          target: build
          context: .
          push: true
          tags: rafsaf/twp-server:${{ github.event.inputs.tag }}
          platforms: linux/amd64,linux/arm64

  redeploy_prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.tag == 'latest' }}
    needs: push_latest_image_to_dockerhub
    steps:
      - uses: actions/checkout@v4
      - name: Redeploy prod server
        run: |
          curl -k -X POST https://${{ secrets.PROD_HOOK_IP }}:9000/hooks/redeploy -H "Content-Type: application/json" -d '{"secret": "${{ secrets.PROD_HOOK_SECRET }}"}'
