name: Manual push stage images to dockerhub and redeploy stage

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "stage"
jobs:
  push_stage_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push stage twp-server image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.prod
          context: .
          push: true
          tags: rafsaf/twp-server:${{ github.event.inputs.tag }}
          platforms: linux/amd64,linux/arm64

  redeploy_stage:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.tag == 'stage' }}
    needs: push_stage_image_to_dockerhub
    steps:
      - uses: actions/checkout@v3
      - name: Redeploy stage server
        run: |
          curl -k -X POST https://${{ secrets.STAGE_HOOK_IP }}:9000/hooks/redeploy -H "Content-Type: application/json" -d '{"secret": "${{ secrets.STAGE_HOOK_SECRET }}"}'
