name: Push stage images to dockerhub and redeploy stage

on:
  workflow_run:
    workflows:
      - "Run pytest based tests"
    branches:
      - master
    types:
      - completed
    tags-ignore:
      - "*.*"
jobs:
  push_stage_image_to_dockerhub:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push stage twp-server image
        uses: docker/build-push-action@v4
        with:
          target: build
          context: .
          push: true
          tags: rafsaf/twp-server:stage
          platforms: linux/amd64 #,linux/arm64

  redeploy_stage:
    runs-on: ubuntu-latest
    needs: push_stage_image_to_dockerhub
    steps:
      - uses: actions/checkout@v4
      - name: Redeploy stage server
        run: |
          curl -k -X POST https://${{ secrets.STAGE_HOOK_IP }}:9000/hooks/redeploy -H "Content-Type: application/json" -d '{"secret": "${{ secrets.STAGE_HOOK_SECRET }}"}'
